# Сравнение чисел обусловленности для матрицы Вандермонда и её корня
## 37 вариант

In [2]:
import numpy as np
import math
from pandas import DataFrame

Реализация обобщенной матрицы Вандермонда и пример для n = 3.

In [3]:
def a_k(k):
    return k*k

def b_k(k):
    return k/2

def Vandermonde_matrix(n):
    A = np.zeros((n, n))
    for i in range (n):
        for j in range (n):
           A[i][j] = a_k(i+1) ** b_k(j+1)
    return A  

print(Vandermonde_matrix(3))

[[ 1.  1.  1.]
 [ 2.  4.  8.]
 [ 3.  9. 27.]]


Реализация функций для нахождения корня матрицы: первая - через собственные числа и векторы, вторая - метод Ньютона.

In [6]:
def first_method(A):
    W, V = np.linalg.eig(A)
    A1 = np.diag(W ** 0.5)
    return V.dot(A1).dot(np.linalg.inv(V))

def second_method(A):
    B_k = A
    B_k1 = 0.5*(B_k + np.linalg.inv(B_k).dot(A))
    diff = np.linalg.norm(B_k1 - B_k)
    while np.linalg.norm(B_k1 - B_k) <= diff:
        diff = np.linalg.norm(B_k1 - B_k)
        B_k = B_k1
        B_k1 = 0.5*(B_k + np.linalg.inv(B_k).dot(A))
    return B_k1  

print(first_method(Vandermonde_matrix(3)), second_method(Vandermonde_matrix(3)), sep='\n\n')

[[0.83705016 0.38699264 0.08939493]
 [0.69282226 1.42988699 1.22919185]
 [0.34934781 1.37269546 5.02806762]]

[[0.83705016 0.38699264 0.08939493]
 [0.69282226 1.42988699 1.22919185]
 [0.34934781 1.37269546 5.02806762]]


Таблица чисел обусловленности для матрицы А и её корня В, вычисленного двумя способами.

In [155]:
table = []

for i in range (2,11):
    A = Vandermonde_matrix(i)
    B1 = first_method(A)
    B2 = second_method(A)
    table.append([i, np.linalg.cond(A), np.linalg.cond(B1), np.linalg.cond(B2)])

df = DataFrame(table, columns = ["n", "cond(A)", "cond(B1)", "cond(B2)"])  
df

n       cond(A)      cond(B1)      cond(B2)
0   2  1.090833e+01  3.325118e+00  3.325118e+00
1   3  1.412356e+02  1.192980e+01  1.192980e+01
2   4  2.501239e+03  5.016987e+01  5.016987e+01
3   5  5.689579e+04  2.401337e+02  2.851804e+02
4   6  1.589237e+06  1.280237e+03  1.899625e+07
5   7  5.284356e+07  7.494255e+03  1.388495e+08
6   8  2.042493e+09  4.765027e+04  3.270624e+12
7   9  9.005984e+10  3.262291e+05  1.603934e+15
8  10  4.462621e+12  2.387685e+06  1.650575e+12