# Сравнение чисел обусловленности для матрицы Вандермонда и её корня
## 37 вариант

In [2]:
import numpy as np
from pandas import DataFrame

Реализация обобщенной матрицы Вандермонда и пример для n = 3.

In [3]:
def a_k(k):
    return k*k

def b_k(k):
    return k/2

def Vandermonde_matrix(n):
    A = np.zeros((n, n))
    for i in range (n):
        for j in range (n):
           A[i][j] = a_k(i+1) ** b_k(j+1)
    return A  

print(Vandermonde_matrix(3))

[[ 1.  1.  1.]
 [ 2.  4.  8.]
 [ 3.  9. 27.]]


Реализация функций для нахождения корня матрицы: первая - через собственные числа и векторы, вторая - метод Ньютона.

In [4]:
def first_method(A):
    W, V = np.linalg.eig(A)
    A1 = np.diag(W ** 0.5)
    return V.dot(A1).dot(np.linalg.inv(V))

def second_method(A):
    B_k = A
    B_k1 = 0.5*(B_k + np.linalg.inv(B_k).dot(A))
    diff = np.linalg.norm(B_k1 - B_k)
    while np.linalg.norm(B_k1 - B_k) <= diff:
        diff = np.linalg.norm(B_k1 - B_k)
        B_k = B_k1
        B_k1 = 0.5*(B_k + np.linalg.inv(B_k).dot(A))
    return B_k1  

print(first_method(Vandermonde_matrix(3)), second_method(Vandermonde_matrix(3)), sep='\n\n')

[[0.83705016 0.38699264 0.08939493]
 [0.69282226 1.42988699 1.22919185]
 [0.34934781 1.37269546 5.02806762]]

[[0.83705016 0.38699264 0.08939493]
 [0.69282226 1.42988699 1.22919185]
 [0.34934781 1.37269546 5.02806762]]


Таблица чисел обусловленности для матрицы А и её корня В, вычисленного двумя способами.

In [8]:
table = []

for i in range (2,11):
    A = Vandermonde_matrix(i)
    B1 = first_method(A)
    B2 = second_method(A)
    table.append([i, np.linalg.cond(A), np.linalg.cond(B1), np.linalg.cond(B2), np.linalg.norm(B1.dot(B1)-A), np.linalg.norm(B2.dot(B2)-A)])

df = DataFrame(table, columns = ["n", "cond(A)", "cond(B1)", "cond(B2)", "norm(B1*B1-A)", "norm(B2*B2-A)"])  
df

n       cond(A)      cond(B1)      cond(B2)  norm(B1*B1-A)  norm(B2*B2-A)
0   2  1.090833e+01  3.325118e+00  3.325118e+00   1.174950e-15   8.005932e-16
1   3  1.412356e+02  1.192980e+01  1.192980e+01   2.405216e-14   1.149344e-09
2   4  2.501239e+03  5.016987e+01  5.016986e+01   3.893604e-13   4.656487e-04
3   5  5.689579e+04  2.401337e+02  1.327909e+03   2.296464e-12   7.199654e+03
4   6  1.589237e+06  1.280237e+03  1.625324e+05   1.372230e-11   5.845044e+05
5   7  5.284356e+07  7.494255e+03  2.467778e+09   1.027460e-09   1.480126e+09
6   8  2.042493e+09  4.765027e+04  4.607792e+07   2.042386e-08   1.406977e+10
7   9  9.005984e+10  3.262291e+05  3.363003e+10   2.152676e-07   2.555743e+13
8  10  4.462621e+12  2.387685e+06  4.722471e+14   7.644593e-06   5.499297e+17

Исходная матрица имеет большие числа обусловленности. У корня, найденного первым способом, они меньше, то есть она более устойчива, и маленькая погрешность. У корня, найденного методом Ньютона, начиная с n = 5 числа обусловленности большие и гораздо хуже погрешность. Решать СЛАУ следует путём регуляризации первым способом.